apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "bookstore.selectorLabels" . | nindent 4 }}
    app: backend
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
