# templates/db-deployment.yaml: ไฟล์ Template สำหรับสร้าง Deployment ของ Database โดยใช้ค่าจาก values.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name }}
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bookstore.selectorLabels" . | nindent 6 }}
      app: db
  template:
    metadata:
      labels:
        {{- include "bookstore.selectorLabels" . | nindent 8 }}
        app: db
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
        ports:
        - containerPort: {{ .Values.database.service.port }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: DB_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: DB_NAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: db-init
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes:
      - name: db-init
        configMap:
          name: bookstore-config
          items:
          - key: init.sql
            path: init.sql
