apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secret
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
